version: '2'
services:
    ng-app:
        image: ng
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ng-postgresql:5432/ng
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ng-postgresql:
        extends:
            file: postgresql.yml
            service: ng-postgresql
